from tkinter import *
def  click(event):
    global scval
    text= event.widget.cget("text")
    print(text)
    if text == "=":
        if scval.get().isdigit():
            value = int(scval.get())
        else:
            value = eval(screen.get())
        
        scval.set(value)
        screen.update()
    elif text == "C":
        scval.set("")
        screen.update()
    else:
        scval.set(scval.get() + text)
        screen.update()
root = Tk()
root.geometry("400x650")
root.title("a simple calculator by umang pahuja")
#root.wm_iconbitmap("1.ico")
root.configure(background="grey")
scval= StringVar()
scval.set("")
screen = Entry(root, textvar=scval,font="grotesk 60 bold")
screen.pack(fill=X, ipadx=10,pady=4,padx=4)
#repeating part
f = Frame(root, bg="white")
b = Button(f,text="9",font="lucida 35 bold")
b.pack(side="left", padx=4 ,pady=4)
b.bind("<Button-1>" , click)
b = Button(f,text="4",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>", click)
b = Button(f,text="7",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>" , click)
f.pack()
f = Frame(root, bg="white")
b = Button(f,text="4",font="lucida 35 bold")
b.pack(side="left", padx=4 ,pady=4)
b.bind("<Button-1>" , click)
b = Button(f,text="5",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>", click)
b = Button(f,text="4",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>" , click)
f.pack()
f = Frame(root, bg="white")
b = Button(f,text="3",font="lucida 35 bold")
b.pack(side="left", padx=4 ,pady=4)
b.bind("<Button-1>" , click)
b = Button(f,text="2",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>", click)
b = Button(f,text="1",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>" , click)
f.pack()
f = Frame(root, bg="white")
b = Button(f,text="0",font="lucida 35 bold")
b.pack(side="left", padx=4 ,pady=4)
b.bind("<Button-1>" , click)
b = Button(f,text="-",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>", click)
b = Button(f,text="+",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>" , click)
f.pack()
f = Frame(root, bg="white")
b = Button(f,text="/",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>" , click)
b = Button(f,text="*",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>" , click)
b = Button(f,text="%",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>" , click)
f.pack()
f = Frame(root, bg="white")
b = Button(f,text="=",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>" , click)
b = Button(f,text="C",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>" , click)
b = Button(f,text=".",font="lucida 35 bold")
b.pack(side="left",padx=4 ,pady=4)
b.bind("<Button-1>" , click)

f.pack()
root.mainloop()